# Generated by Django 5.0.6 on 2024-06-21 22:05

import django.db.models.deletion
import month.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydailybudget',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customactivity',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customactivity',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailybudget',
            name='minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailybudget',
            name='plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailybudget',
            name='total_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('monthly_budget', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
