# Generated by Django 5.0.6 on 2024-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_activity_price_alter_activity_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='customactivity',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='dailybudget',
            name='original',
            field=models.IntegerField(default=0),
        ),
    ]
