# Generated by Django 5.0.6 on 2024-06-24 11:11

import month.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_activity_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=month.models.MonthField(null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='monthly_budget',
            field=models.IntegerField(null=True),
        ),
    ]
