# Generated by Django 5.0.6 on 2024-06-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_monthlybudget_month_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monthlybudget',
            table='MonthlyBudget',
        ),
    ]
