# Generated by Django 5.0.6 on 2024-06-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_monthlybudget_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
    ]
