# Generated by Django 5.0.6 on 2024-08-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_delete_monthlybudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybudget',
            name='original',
        ),
    ]
